const donationData = [
    {
        id: 1,
        date: "2023-10-01",
        quantity: "5 kg",
        location: "Berlin, Germany",
        status: "Completed",
        price: "25 €",
        type: "Fruits and vegetables",
        beneficiary: "Berlin Food Bank",
        image: require("../assets/plan1.jpg"),
        description: "Fresh fruits and vegetables donated to support local communities.",
        contact: "info@berlinfoodbank.de",
        deliveryMethod: "Pickup",
    },
    {
        id: 2,
        date: "2023-09-25",
        quantity: "3 kg",
        location: "Munich, Germany",
        status: "Completed",
        price: "15 €",
        type: "Dairy products",
        beneficiary: "Munich Food Aid",
        image: require("../assets/plan2.jpg"),
        description: "Dairy products including milk, cheese, and yogurt.",
        contact: "contact@munichfoodaid.org",
        deliveryMethod: "Delivery",
    },
    {
        id: 3,
        date: "2023-09-20",
        quantity: "10 kg",
        location: "Hamburg, Germany",
        status: "Completed",
        price: "50 €",
        type: "Breads and pastries",
        beneficiary: "Hamburg Community Kitchen",
        image: require("../assets/plan3.jpg"),
        description: "Freshly baked bread and pastries donated daily.",
        contact: "support@hamburgkitchen.de",
        deliveryMethod: "Pickup",
    },
    {
        id: 4,
        date: "2023-09-15",
        quantity: "8 kg",
        location: "Frankfurt, Germany",
        status: "Pending",
        price: "40 €",
        type: "Canned goods",
        beneficiary: "Frankfurt Food Rescue",
        image: require("../assets/plan4.jpg"),
        description: "Canned vegetables, soups, and beans for long-term storage.",
        contact: "help@frankfurtrescue.org",
        deliveryMethod: "Delivery",
    },
    {
        id: 5,
        date: "2023-09-10",
        quantity: "12 kg",
        location: "Cologne, Germany",
        status: "Completed",
        price: "60 €",
        type: "Meat and poultry",
        beneficiary: "Cologne Food Support",
        image: require("../assets/plan5.jpg"),
        description: "High-quality meat and poultry donated by local farms.",
        contact: "donate@colognefood.org",
        deliveryMethod: "Pickup",
    },
];

export default donationData;