import { Platform, StyleSheet } from 'react-native';

export const COLORS = {
    primary: '#FF6F61',
    secondary: '#6A549E',
    background: '#fefefe',
    card: '#FFFFFF',
    text: '#2C2C2C',
    accent: '#FF5252',
    border: '#F1D4E5',
    shadow: 'rgba(0, 0, 0, 0.1)',
};

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    mapContainer: {
        marginBottom: 16,
        height: 250,
        width: '100%',
        borderBottomEndRadius: 15,
        borderBottomLeftRadius: 15,
        overflow: 'hidden',
    },
    map: {
        width: '100%',
        height: '100%',
    },
    searchBarContainer: {
        position: 'absolute',
        top: 16,
        left: 16,
        right: 16,
        zIndex: 1,
    },
    searchBarContent: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 3,
        borderColor: COLORS.border,
        borderWidth: 1,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    searchIcon: {
        marginLeft: 8,
    },
    searchBar: {
        flex: 1,
        fontSize: 16,
        color: COLORS.text,
    },
    contentContainer: {
        paddingHorizontal: 15,
        paddingBottom: 20,
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginRight: 16,
        marginBottom: 16,
    },
    screenTitle: {
        fontSize: 24,
        fontWeight: 'bold',
    },
    screenSubtitle: {
        fontSize: 16,
        color: COLORS.text,
        marginBottom: 20,
    },
    addButton: {
        backgroundColor: '#F4BF96',
        paddingVertical: 14,
        borderRadius: 5,
        alignItems: 'center',
        marginBottom: 20,
    },
    addButtonContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    addButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        marginLeft: 8,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: COLORS.text,
        marginBottom: 15,
    },
    noDonationsText: {
        fontSize: 16,
        color: COLORS.text,
        textAlign: 'center',
        marginTop: 20,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContainer: {
        backgroundColor: COLORS.card,
        padding: 25,
        borderRadius: 8,
        width: '90%',
        maxHeight: '82%', // Hauteur maximale du modal
    },
    modalContent: {
        width: '100%',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.text,
        marginBottom: 20,
    },
    selectedImage: {
        width: '100%',
        height: 100,
        borderRadius: 8,
        marginVertical: 8,
    },
    input: {
        backgroundColor: '#f5f5f5',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: Platform.OS === 'ios' ? 10 : 8,
        height: 40,
        fontSize: 16,
        borderWidth: 1,
        borderColor: COLORS.border,
        color: COLORS.text,
        marginBottom: 10,
    },
    modalButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 16,
    },
    button: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 5,
    },
    saveButton: {
        backgroundColor: '#889E73',
    },
    cancelButton: {
        backgroundColor: '#BFBBA9',
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: 'bold',
    },
    cancelButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: 'bold',
    },
    imagePickerContainer: {
        width: 120,
        height: 120,
        borderWidth: 2,
        borderColor: '#ccc',
        borderStyle: 'dashed',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
        overflow: 'hidden',
    },
    imagePreview: {
        width: '100%',
        height: '100%',
    },
    imagePlaceholder: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    imagePlaceholderText: {
        color: '#888',
        marginTop: 8,
        fontSize: 12,
    },
    noDonationsContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
    },
    noDonationsText: {
        textAlign: 'center',
        color: '#888',
        fontSize: 16,
        marginTop: 10,
        marginBottom: 20,
    },
    recurringContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    notificationButton: {
        backgroundColor: COLORS.primary,
        padding: 12,
        borderRadius: 5,
        alignItems: 'center',
        margin: 16,
    },
    notificationButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },

    dropDownContainer: {
        borderColor: '#CCC',
        borderWidth: 1,
        borderRadius: 8,
        marginTop: 5,
    },
    input: {
        borderWidth: 1,
        borderColor: '#CCC',
        borderRadius: 8,
        padding: 10,
        marginBottom: 15,
        backgroundColor: '#FFF',
        zIndex: 1,
    },
});